# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_to_db',
            new_name='Fs_database',
        ),
    ]
